"use client";

import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowClockwise, CheckCircle, Sparkle } from "@phosphor-icons/react";
import type { AIFeatureId } from "./types";
import { getAIFeature } from "./ai-feature-catalog";
import { AIAnalysisHeader } from "./shared/AIAnalysisHeader";
import { AIAnalysisLoading } from "./shared/AIAnalysisLoading";
import { AIEmptyState } from "./shared/AIEmptyState";
import { AILimitationNotice } from "./shared/AILimitationNotice";

type Config = { inputLabel: string; placeholder: string; resultTitle: string; result: string; metrics: string[]; evidence: string[]; gaps: string[]; actions: string[] };
const configs: Record<Exclude<AIFeatureId, "collaboration-matching" | "innovation-profile" | "innovation-workspace">, Config> = {
  "research-gap": { inputLabel: "Topik atau konteks riset", placeholder: "Monitoring kualitas air berbasis sensor", resultTitle: "Gap themes dan peluang ide", result: "Data simulasi menunjukkan ruang eksplorasi pada kalibrasi sensor murah, ketahanan perangkat, dan interpretasi data lapangan.", metrics: ["3 gap themes", "2 peluang ide", "Confidence sedang"], evidence: ["Ringkasan AquaLoop", "Field dataset v2", "Laporan uji lapangan (pending)"], gaps: ["Corpus riset prototype tidak lengkap", "Belum ada validasi literatur eksternal"], actions: ["Susun pertanyaan riset", "Tambahkan sumber", "Validasi dengan peneliti"] },
  "novelty-checker": { inputLabel: "Judul dan ringkasan ide", placeholder: "Sistem monitoring air adaptif berbasis sensor murah", resultTitle: "Indikasi kebaruan", result: "Diferensiasi awal terlihat pada kombinasi kalibrasi adaptif dan konteks distribusi lokal. Kemiripan ditemukan pada tema monitoring sensor umum.", metrics: ["Indikasi 64/100", "2 overlap themes", "1 differentiator"], evidence: ["Data pembanding simulasi", "Spesifikasi prototype"], gaps: ["Bukan pencarian prior art resmi", "Memerlukan validasi database resmi"], actions: ["Perjelas differentiator", "Bandingkan klaim teknis", "Konsultasi HKI"] },
  "industry-matching": { inputLabel: "Kebutuhan industri", placeholder: "Pilot monitoring air untuk kawasan industri", resultTitle: "Mitra simulasi yang relevan", result: "Aqua Infrastructure Lab memiliki relevansi use case tinggi, tetapi mensyaratkan evidence kestabilan perangkat dan pilot terukur.", metrics: ["Relevansi 78/100", "Readiness requirement: pilot", "Organization access"], evidence: ["Profil organisasi simulasi", "Readiness proyek", "Use case prototype"], gaps: ["Belum ada kontak atau komitmen nyata", "Evidence pilot belum lengkap"], actions: ["Siapkan brief pilot", "Lengkapi evidence", "Tinjau kesiapan mitra"] },
  "funding-recommendation": { inputLabel: "Tujuan pendanaan", placeholder: "Validasi pilot dan perangkat lapangan", resultTitle: "Program simulasi yang berpotensi relevan", result: "Skema Prototype Validation Fund cocok secara tematik, namun eligibility dan dokumen teknis masih harus diverifikasi.", metrics: ["Thematic match 74/100", "Eligibility: perlu review", "Deadline: data simulasi"], evidence: ["Readiness proyek", "Evidence summary", "Program dummy"], gaps: ["Rencana biaya belum tersedia", "Tanggal bukan informasi real-time"], actions: ["Lengkapi anggaran", "Tinjau eligibility", "Siapkan proposal"] },
  commercialization: { inputLabel: "Target pengguna dan use case", placeholder: "Operator distribusi air tingkat kota", resultTitle: "Commercialization pathway", result: "Jalur konservatif adalah validasi problem-solution fit, pilot terbatas, evaluasi IP, lalu kemitraan implementasi.", metrics: ["TRL simulasi: 4", "Problem-solution fit: awal", "Pilot required"], evidence: ["Readiness prototype", "Kebutuhan kolaborasi", "Evidence lapangan"], gaps: ["Belum ada willingness-to-pay", "IP dan model bisnis belum ditinjau"], actions: ["Wawancara pengguna", "Rancang pilot", "Tinjau IP"] },
};

export function AIExperiencePage({ featureId }: { featureId: keyof typeof configs }) {
  const feature = getAIFeature(featureId)!; const config = configs[featureId]; const params = useSearchParams();
  const [input, setInput] = useState(params.get("project") ?? params.get("organization") ?? "");
  const [status, setStatus] = useState<"idle" | "loading" | "result" | "empty" | "error">("idle");
  const run = () => { if (!input.trim()) return setStatus("empty"); setStatus("loading"); window.setTimeout(() => setStatus("result"), 450); };
  return <div className="ai-page"><AIAnalysisHeader title={feature.title} description={feature.description} /><section className="ai-input-card"><label htmlFor={`${featureId}-input`}>{config.inputLabel}</label><textarea id={`${featureId}-input`} value={input} onChange={(event) => setInput(event.target.value)} placeholder={config.placeholder} /><div className="ai-actions"><button className="button primary" type="button" onClick={run}><Sparkle aria-hidden="true" /> Jalankan simulasi</button><button className="button ghost" type="button" onClick={() => { setInput(""); setStatus("idle"); }}><ArrowClockwise aria-hidden="true" /> Reset</button></div></section>{status === "loading" ? <AIAnalysisLoading /> : status === "empty" ? <AIEmptyState title="Konteks belum tersedia" description="Masukkan konteks agar simulasi dapat dijalankan."><button type="button" className="button secondary" onClick={() => setStatus("idle")}>Kembali ke input</button></AIEmptyState> : status === "error" ? <AIEmptyState title="Simulasi tidak dapat diselesaikan" description="Coba kembali dengan konteks yang lebih spesifik."><button type="button" className="button secondary" onClick={run}>Coba lagi</button></AIEmptyState> : status === "result" ? <section className="ai-result" aria-live="polite"><div className="ai-result__hero"><CheckCircle size={28} aria-hidden="true" /><div><p>Hasil simulasi</p><h2>{config.resultTitle}</h2><span>{config.result}</span></div></div><div className="ai-metric-grid">{config.metrics.map((item) => <div key={item}>{item}</div>)}</div><div className="ai-three-column"><section><h3>Evidence/source</h3><ul>{config.evidence.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h3>Data gap</h3><ul>{config.gaps.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h3>Next action</h3><ul>{config.actions.map((item) => <li key={item}>{item}</li>)}</ul></section></div><AILimitationNotice limitation={{ id: `${featureId}-limit`, title: "Data simulasi prototype", description: feature.limitationSummary }} /></section> : null}</div>;
}
