import { dummyProjects } from "./registry/projects";
import { dummyOrganizations } from "./registry/organizations";

function projectSearchProjection(project: (typeof dummyProjects)[number]): SearchItem {
  const organization = dummyOrganizations.find((o) => o.id === project.organizationId);
  return {
    id: `project-${project.slug}`,
    slug: project.slug,
    scope: "projects",
    title: project.title,
    owner: organization?.displayName ?? "Unknown",
    summary: project.problem,
    field: "Environmental Data",
    location: project.location ?? "Bandung",
    status: project.lifecycle,
    readiness: project.readiness,
    verification: `Status ${project.readinessSource}`,
    evidence: [`${project.evidenceSummary.total} sumber tersedia`],
    reasons: ["Masalah dan teknologi relevan", "Evidence publik tersedia"],
    gaps: ["Membutuhkan validasi di lokasi kedua"],
    href: `/projects/${project.slug}`,
    technologies: ["IoT Sensors", "Data Pipeline", "Python"],
    collaborationNeeds: ["Embedded Systems Contributor", "Data Engineer"],
    workMode: project.mode === "Hybrid" ? "HYBRID" : "REMOTE",
    organizationId: project.organizationId,
    evidenceCount: project.evidenceSummary.total,
    updatedAt: "2026-07-15",
  };
}

const aquaLoopProject = dummyProjects.find((p) => p.slug === "aqua-loop")!;

export const PROTOTYPE_REFERENCE_DATE = "2026-07-24";

export type SearchScope =
  | "projects"
  | "people"
  | "organizations"
  | "opportunities";

export type SearchItem = {
  id: string;
  slug: string;
  scope: SearchScope;
  title: string;
  owner: string;
  summary: string;
  field: string;
  location: string;
  status: string;
  readiness?: string;
  availability?: string;
  commitment?: string;
  verification: string;
  evidence: string[];
  reasons: string[];
  gaps: string[];
  href: string;
  skills?: string[];
  technologies?: string[];
  profileType?: string;
  experienceLevel?: string;
  organizationType?: string;
  organizationSize?: string;
  acceptsCollaboration?: boolean;
  opportunityType?: string;
  requiredSkills?: string[];
  collaborationNeeds?: string[];
  workMode?: "REMOTE" | "ON_SITE" | "HYBRID";
  evidenceCount?: number;
  projectCount?: number;
  activeOpportunityCount?: number;
  deadline?: string;
  daysUntilDeadline?: number;
  updatedAt?: string;
  organizationId?: string;
};

export const searchItems: SearchItem[] = [
  projectSearchProjection(aquaLoopProject),
  {
    id: "project-industrial-motor",
    slug: "industrial-motor-monitoring",
    scope: "projects",
    title: "Industrial Motor Predictive Monitoring",
    owner: "Nexa Research Lab",
    summary: "Deteksi dini anomali motor industri menggunakan data getaran.",
    field: "Predictive Maintenance",
    location: "Bandung",
    status: "ACTIVE",
    readiness: "PROTOTYPE",
    verification: "Readiness dilaporkan pemilik proyek",
    evidence: ["Prototype signal classifier", "Benchmark dataset"],
    reasons: ["Kebutuhan computer vision dan sensor", "Terbuka untuk pilot"],
    gaps: ["Dataset produksi belum tersedia"],
    href: "/projects/industrial-motor-monitoring",
    technologies: ["Vibration Sensors", "Python", "TensorFlow"],
    collaborationNeeds: ["Signal Classifier Contributor", "Computer Vision Researcher"],
    workMode: "REMOTE",
    organizationId: "nexa-research-lab",
    evidenceCount: 2,
    updatedAt: "2026-07-20",
  },
  {
    id: "project-smart-cooling",
    slug: "smart-cooling",
    scope: "projects",
    title: "Smart Cooling for Community Cold Chain",
    owner: "Agri Nexus",
    summary: "Optimasi rantai dingin hasil tani dengan sensor hemat energi.",
    field: "IoT",
    location: "Yogyakarta",
    status: "ACTIVE",
    readiness: "TESTING",
    verification: "Pengujian dikonfirmasi mitra",
    evidence: ["Hardware test log"],
    reasons: ["Mencari kolaborator embedded", "Pengujian aktif"],
    gaps: ["Belum ada data konsumsi satu musim"],
    href: "/projects/smart-cooling",
    technologies: ["LoRaWAN", "ESP32", "Thermal Sensors"],
    collaborationNeeds: ["Firmware Engineer", "IoT Specialist"],
    workMode: "ON_SITE",
    organizationId: "arunika-innovation-hub",
    evidenceCount: 1,
    updatedAt: "2026-07-18",
  },
  {
    id: "project-climate-microgrid",
    slug: "climate-microgrid",
    scope: "projects",
    title: "Solar Microgrid & Energy Analytics",
    owner: "Nexa Research Lab",
    summary: "Monitoring efisiensi panel surya dan penyimpanan baterai skala komunitas.",
    field: "Climate Technology",
    location: "Bandung",
    status: "ACTIVE",
    readiness: "PILOT",
    verification: "Pilot aktif dengan 12 sensor terpasang",
    evidence: ["Telemetry dashboard log", "Grid stability benchmark"],
    reasons: ["Kebutuhan IoT dan analytics", "Terbuka untuk riset gabungan"],
    gaps: ["Kalibrasi sensor arus frekuensi tinggi"],
    href: "/projects/industrial-motor-monitoring",
    technologies: ["IoT", "Python", "Thermal Sensors", "PostgreSQL"],
    collaborationNeeds: ["Data Engineer", "IoT Specialist"],
    workMode: "HYBRID",
    organizationId: "nexa-research-lab",
    evidenceCount: 3,
    updatedAt: "2026-07-23",
  },
  {
    id: "project-forest-fire-detection",
    slug: "forest-fire-detection",
    scope: "projects",
    title: "Early Forest Fire Detection Satellite AI",
    owner: "Nusantara Labs",
    summary: "Deteksi titik panas dan asap hutan menggunakan citra satelit realtime.",
    field: "Computer Vision",
    location: "Jakarta",
    status: "ACTIVE",
    readiness: "RESEARCH",
    verification: "Dataset dan model divalidasi peneliti",
    evidence: ["Thermal anomaly benchmark", "Satellite dataset"],
    reasons: ["Membutuhkan peneliti vision dan geospatial"],
    gaps: ["Resolusi citra waktu malam masih terbatas"],
    href: "/projects/industrial-motor-monitoring",
    technologies: ["PyTorch", "OpenCV", "PostgreSQL", "Geospatial"],
    collaborationNeeds: ["Computer Vision Researcher"],
    workMode: "REMOTE",
    organizationId: "nusantara-labs",
    evidenceCount: 2,
    updatedAt: "2026-07-21",
  },
  {
    id: "project-urban-flood-sensor",
    slug: "urban-flood-sensor",
    scope: "projects",
    title: "Urban Flood Early Warning Network",
    owner: "Arunika Innovation Hub",
    summary: "Jaringan sensor ketinggian air dan curah hujan berbasis LoRaWAN.",
    field: "Urban Systems",
    location: "Surabaya",
    status: "ACTIVE",
    readiness: "TESTING",
    verification: "Pengujian jaringan dikonfirmasi pemerintah kota",
    evidence: ["Sensor telemetry report"],
    reasons: ["Integrasi hardware dan telemetry"],
    gaps: ["Daya tahan baterai saat banjir bandang"],
    href: "/projects/smart-cooling",
    technologies: ["LoRaWAN", "ESP32", "Data Pipeline"],
    collaborationNeeds: ["Embedded Systems Engineer", "Data Pipeline"],
    workMode: "ON_SITE",
    organizationId: "arunika-innovation-hub",
    evidenceCount: 2,
    updatedAt: "2026-07-19",
  },
  {
    id: "person-maya",
    slug: "maya-pradipta",
    scope: "people",
    title: "Maya Pradipta",
    owner: "Data Engineer",
    summary: "Data pipeline, environmental sensing, dan open research.",
    field: "Environmental Data",
    location: "Bandung",
    status: "AVAILABLE",
    availability: "AVAILABLE",
    verification: "Identitas dan 2 kontribusi dikonfirmasi",
    evidence: ["AquaLoop pipeline", "2 repository publik"],
    reasons: ["3 kebutuhan proyek cocok", "Tersedia 8 jam/minggu"],
    gaps: ["Belum memiliki evidence deployment skala produksi"],
    href: "/profiles/maya-pradipta",
    profileType: "Data Engineer",
    skills: ["Python", "Spark", "PostgreSQL", "Data Pipeline"],
    experienceLevel: "Senior",
    organizationId: "nexa-research-lab",
    evidenceCount: 3,
    projectCount: 2,
    updatedAt: "2026-07-22",
  },
  {
    id: "person-nadia",
    slug: "nadia-putri",
    scope: "people",
    title: "Nadia Putri",
    owner: "Computer Vision Researcher",
    summary: "Computer vision untuk inspeksi industri dan citra termal.",
    field: "Computer Vision",
    location: "Jakarta",
    status: "AVAILABLE",
    availability: "AVAILABLE",
    verification: "Identitas dikonfirmasi; evidence self-reported",
    evidence: ["Thermal anomaly benchmark"],
    reasons: ["Keahlian computer vision cocok", "Pernah mengerjakan inspeksi"],
    gaps: ["Ketersediaan setelah September"],
    href: "/profiles/nadia-putri",
    profileType: "Computer Vision Researcher",
    skills: ["PyTorch", "OpenCV", "Thermal Imaging"],
    experienceLevel: "Lead",
    organizationId: "nusantara-labs",
    evidenceCount: 2,
    projectCount: 3,
    updatedAt: "2026-07-21",
  },
  {
    id: "person-arya",
    slug: "arya-santoso",
    scope: "people",
    title: "Arya Santoso",
    owner: "Embedded Systems Engineer",
    summary: "Firmware, low-power sensors, dan prototyping perangkat.",
    field: "IoT",
    location: "Surabaya",
    status: "PRIVATE_AVAILABILITY",
    availability: "PRIVATE",
    verification: "1 kontribusi dikonfirmasi organisasi",
    evidence: ["Sensor calibration firmware"],
    reasons: ["Kebutuhan embedded cocok"],
    gaps: ["Availability tidak dipublikasikan"],
    href: "/profiles/arya-santoso",
    profileType: "Embedded Systems Engineer",
    skills: ["C/C++", "FreeRTOS", "Circuit Design"],
    experienceLevel: "Mid",
    organizationId: "arunika-innovation-hub",
    evidenceCount: 1,
    projectCount: 1,
    updatedAt: "2026-07-15",
  },
  {
    id: "person-budi",
    slug: "budi-pratama",
    scope: "people",
    title: "Budi Pratama",
    owner: "IoT & Hardware Lead",
    summary: "Spesialis sensor nirkabel, LoRaWAN, dan riset perangkat keras.",
    field: "IoT",
    location: "Yogyakarta",
    status: "AVAILABLE",
    availability: "AVAILABLE",
    verification: "4 kontribusi hardware dikonfirmasi",
    evidence: ["LoRaWAN gateway node", "Hardware test log"],
    reasons: ["Tersedia untuk pilot rantai dingin dan banjir"],
    gaps: ["Terbatas untuk proyek luar kota"],
    href: "/profiles/arya-santoso",
    profileType: "Embedded Systems Engineer",
    skills: ["FreeRTOS", "C/C++", "LoRaWAN", "ESP32"],
    experienceLevel: "Lead",
    organizationId: "arunika-innovation-hub",
    evidenceCount: 4,
    projectCount: 4,
    updatedAt: "2026-07-23",
  },
  {
    id: "person-siti",
    slug: "siti-rahmawati",
    scope: "people",
    title: "Siti Rahmawati",
    owner: "Senior Geospatial Analyst",
    summary: "Pemetaan spasial, pemodelan iklim perkotaan, dan analisis GIS.",
    field: "Geospatial",
    location: "Bandung",
    status: "AVAILABLE",
    availability: "AVAILABLE",
    verification: "Terverifikasi oleh Nexa Research Lab",
    evidence: ["Urban Heat Map dataset", "GIS Pipeline"],
    reasons: ["Keahlian pemetaan iklim sesuai"],
    gaps: ["Hanya tersedia remote"],
    href: "/profiles/maya-pradipta",
    profileType: "Data Engineer",
    skills: ["Python", "Geospatial", "Data Pipeline", "PostgreSQL"],
    experienceLevel: "Senior",
    organizationId: "nexa-research-lab",
    evidenceCount: 3,
    projectCount: 2,
    updatedAt: "2026-07-20",
  },
  {
    id: "org-nexa",
    slug: "nexa-research-lab",
    scope: "organizations",
    title: "Nexa Research Lab",
    owner: "Applied Research Organization",
    summary: "Riset terapan untuk climate technology dan industrial intelligence.",
    field: "Climate Technology",
    location: "Bandung",
    status: "CONFIRMED",
    verification: "Identitas organisasi terverifikasi",
    evidence: ["4 proyek publik", "7 kolaborasi dimulai"],
    reasons: ["Bidang dan lokasi sesuai", "Memiliki peluang terbuka"],
    gaps: ["Beberapa outcome masih self-reported"],
    href: "/organizations/nexa-research-lab",
    organizationType: "Applied Research",
    organizationSize: "50-200",
    acceptsCollaboration: true,
    organizationId: "nexa-research-lab",
    projectCount: 4,
    activeOpportunityCount: 2,
    updatedAt: "2026-07-23",
  },
  {
    id: "org-nusantara",
    slug: "nusantara-labs",
    scope: "organizations",
    title: "Nusantara Labs",
    owner: "Research Partner",
    summary: "Laboratorium data perkotaan dan climate resilience.",
    field: "Urban Systems",
    location: "Jakarta",
    status: "VERIFIED",
    verification: "Identitas organisasi terverifikasi",
    evidence: ["2 proyek publik"],
    reasons: ["Bidang urban systems relevan"],
    gaps: ["Tidak ada peluang aktif"],
    href: "/organizations/nusantara-labs",
    organizationType: "Research Partner",
    organizationSize: "10-50",
    acceptsCollaboration: true,
    organizationId: "nusantara-labs",
    projectCount: 2,
    activeOpportunityCount: 1,
    updatedAt: "2026-07-19",
  },
  {
    id: "org-arunika",
    slug: "arunika-innovation-hub",
    scope: "organizations",
    title: "Arunika Innovation Hub",
    owner: "Innovation Hub",
    summary: "Penghubung pilot industri dan komunitas teknologi.",
    field: "Innovation",
    location: "Surabaya",
    status: "PENDING_VERIFICATION",
    verification: "Verifikasi organisasi sedang diproses",
    evidence: ["1 proyek publik"],
    reasons: ["Memiliki jaringan pilot"],
    gaps: ["Identitas organisasi belum selesai diverifikasi"],
    href: "/organizations/arunika-innovation-hub",
    organizationType: "Innovation Hub",
    organizationSize: "200+",
    acceptsCollaboration: false,
    organizationId: "arunika-innovation-hub",
    projectCount: 1,
    activeOpportunityCount: 0,
    updatedAt: "2026-07-10",
  },
  {
    id: "org-agri",
    slug: "agri-nexus",
    scope: "organizations",
    title: "Agri Nexus",
    owner: "Agritech Innovation Lab",
    summary: "Pengembangan rantai dingin hemat energi dan IoT pertanian.",
    field: "IoT",
    location: "Yogyakarta",
    status: "CONFIRMED",
    verification: "Identitas organisasi dikonfirmasi mitra",
    evidence: ["3 proyek pilot aktif"],
    reasons: ["Pionir cold chain komunitas"],
    gaps: ["Kapasitas tim laboratorium terbatas"],
    href: "/organizations/arunika-innovation-hub",
    organizationType: "Applied Research",
    organizationSize: "10-50",
    acceptsCollaboration: true,
    organizationId: "agri-nexus",
    projectCount: 3,
    activeOpportunityCount: 2,
    updatedAt: "2026-07-21",
  },
  {
    id: "opp-urban-heat",
    slug: "urban-heat-mapping",
    scope: "opportunities",
    title: "Urban Heat Mapping Research Collaboration",
    owner: "Nexa Research Lab",
    summary: "Kolaborasi pemetaan panas perkotaan untuk pilot Bandung.",
    field: "Geospatial",
    location: "Bandung",
    status: "OPEN",
    commitment: "6–8 jam/minggu",
    verification: "Peluang dikonfirmasi organisasi",
    evidence: ["Project brief", "Pilot readiness note"],
    reasons: ["Terbuka untuk data engineer", "Scope kontribusi jelas"],
    gaps: ["Honorarium masih dalam finalisasi"],
    href: "/opportunities/urban-heat-mapping",
    opportunityType: "Research Collaboration",
    requiredSkills: ["Data Pipeline", "Geospatial", "Python"],
    workMode: "HYBRID",
    deadline: "2026-07-28",
    daysUntilDeadline: 4,
    organizationId: "nexa-research-lab",
    updatedAt: "2026-07-22",
  },
  {
    id: "opp-fire-detection",
    slug: "fire-detection-collaboration",
    scope: "opportunities",
    title: "Satellite Image Classifier for Wildfire Prevention",
    owner: "Nusantara Labs",
    summary: "Kontribusi riset model computer vision untuk citra satelit termal.",
    field: "Computer Vision",
    location: "Jakarta",
    status: "OPEN",
    commitment: "5 jam/minggu",
    verification: "Peluang riset terverifikasi",
    evidence: ["Satellite Dataset v2"],
    reasons: ["Kebutuhan riset vision jelas"],
    gaps: ["Waktu pengerjaan fleksibel"],
    href: "/opportunities/urban-heat-mapping",
    opportunityType: "Research Collaboration",
    requiredSkills: ["PyTorch", "OpenCV", "Python"],
    workMode: "REMOTE",
    deadline: "2026-07-30",
    daysUntilDeadline: 6,
    organizationId: "nusantara-labs",
    updatedAt: "2026-07-22",
  },
  {
    id: "opp-embedded",
    slug: "embedded-engineer-pilot",
    scope: "opportunities",
    title: "Embedded Engineer untuk Sensor Pilot",
    owner: "Agri Nexus",
    summary: "Kontribusi firmware dan kalibrasi untuk cold-chain pilot.",
    field: "IoT",
    location: "Yogyakarta",
    status: "OPEN",
    commitment: "4 minggu",
    verification: "Project owner terverifikasi",
    evidence: ["Hardware specification"],
    reasons: ["Output dan durasi jelas"],
    gaps: ["Kompensasi belum dipublikasikan"],
    href: "/opportunities/embedded-engineer-pilot",
    opportunityType: "Sensor Pilot",
    requiredSkills: ["Firmware", "C/C++", "FreeRTOS"],
    workMode: "ON_SITE",
    deadline: "2026-08-15",
    daysUntilDeadline: 22,
    organizationId: "arunika-innovation-hub",
    updatedAt: "2026-07-20",
  },
  {
    id: "opp-microgrid-pilot",
    slug: "microgrid-pilot-collaboration",
    scope: "opportunities",
    title: "Solar Energy Analytics Firmware Engineer",
    owner: "Nexa Research Lab",
    summary: "Peluang pengujian sensor daya dan efisiensi microgrid surya.",
    field: "Climate Technology",
    location: "Bandung",
    status: "OPEN",
    commitment: "3 minggu pilot",
    verification: "Peluang dikonfirmasi Nexa Lab",
    evidence: ["Microgrid spec sheet"],
    reasons: ["Kebutuhan sensor daya"],
    gaps: ["Diutamakan domisili Bandung/sekitarnya"],
    href: "/opportunities/embedded-engineer-pilot",
    opportunityType: "Sensor Pilot",
    requiredSkills: ["IoT", "FreeRTOS", "C/C++"],
    workMode: "HYBRID",
    deadline: "2026-08-05",
    daysUntilDeadline: 12,
    organizationId: "nexa-research-lab",
    updatedAt: "2026-07-23",
  },
  {
    id: "opp-railway",
    slug: "railway-sensor-collaboration",
    scope: "opportunities",
    title: "Railway Sensor Collaboration",
    owner: "Nusantara Labs",
    summary: "Kolaborasi analisis sensor untuk preventive maintenance.",
    field: "Predictive Maintenance",
    location: "Jakarta",
    status: "CLOSED",
    commitment: "Selesai",
    verification: "Status ditutup oleh organisasi",
    evidence: ["Archived opportunity brief"],
    reasons: ["Tersimpan sebagai referensi bidang"],
    gaps: ["Tidak lagi menerima aplikasi"],
    href: "/opportunities/railway-sensor-collaboration",
    opportunityType: "Analysis",
    requiredSkills: ["Vibration Sensors", "Signal Processing", "Python"],
    workMode: "REMOTE",
    deadline: "2026-09-30",
    daysUntilDeadline: 68,
    organizationId: "nusantara-labs",
    updatedAt: "2026-06-30",
  },
];

export const scopeConfig = {
  projects: {
    label: "Proyek",
    queryPlaceholder: "Cari proyek, teknologi, masalah, atau bidang",
    filters: ["field", "readiness", "location", "technology", "lifecycle", "need", "workMode", "ownership"] as const,
    sorts: ["relevance", "recent", "readiness", "evidence"] as const,
  },
  people: {
    label: "Orang",
    queryPlaceholder: "Cari nama, keahlian, peran, atau institusi",
    filters: ["field", "availability", "location", "profileType", "skill", "experience", "ownership"] as const,
    sorts: ["relevance", "evidence", "projects", "recent"] as const,
  },
  organizations: {
    label: "Organisasi",
    queryPlaceholder: "Cari nama, fokus, sektor, atau lokasi",
    filters: ["field", "location", "organizationType", "size", "acceptsCollab", "ownership"] as const,
    sorts: ["relevance", "projects", "opportunities", "recent"] as const,
  },
  opportunities: {
    label: "Peluang",
    queryPlaceholder: "Cari peran, bidang, proyek, atau organisasi",
    filters: ["field", "location", "status", "opportunityType", "requiredSkill", "workMode", "deadlineRange", "ownership"] as const,
    sorts: ["relevance", "deadline", "recent"] as const,
  },
} satisfies Record<SearchScope, {
  label: string;
  queryPlaceholder: string;
  filters: readonly string[];
  sorts: readonly string[];
}>;

export const filterLabels: Record<string, string> = {
  field: "Bidang",
  readiness: "Kesiapan",
  availability: "Ketersediaan",
  location: "Lokasi",
  status: "Status",
  profileType: "Peran / Tipe Profil",
  organizationType: "Tipe Organisasi",
  opportunityType: "Tipe Peluang",
  skill: "Keahlian (Skill)",
  experience: "Tingkat Pengalaman",
  technology: "Teknologi",
  lifecycle: "Lifecycle Status",
  need: "Kebutuhan Kolaborasi",
  workMode: "Mode Kerja",
  size: "Ukuran Organisasi",
  acceptsCollab: "Menerima Kolaborasi",
  requiredSkill: "Skill Dibutuhkan",
  deadlineRange: "Tenggat Waktu",
  organization: "Konteks Organisasi",
  ownership: "Entitas Kepemilikan",
};

export const filterOptions: Record<string, string[]> = {
  field: ["Environmental Data", "Predictive Maintenance", "Computer Vision", "IoT", "Climate Technology", "Geospatial", "Urban Systems", "Innovation"],
  readiness: ["RESEARCH", "PROTOTYPE", "TESTING", "PILOT", "IMPLEMENTED"],
  availability: ["AVAILABLE", "PRIVATE"],
  location: ["Bandung", "Jakarta", "Yogyakarta", "Surabaya"],
  status: ["OPEN", "CLOSED", "ACTIVE", "CONFIRMED", "VERIFIED", "PENDING_VERIFICATION"],
  profileType: ["Data Engineer", "Computer Vision Researcher", "Embedded Systems Engineer"],
  organizationType: ["Applied Research", "Research Partner", "Innovation Hub"],
  opportunityType: ["Research Collaboration", "Sensor Pilot", "Analysis"],
  ownership: ["all", "internal", "external"],
};

function cleanStrings(items: (string | undefined)[]): string[] {
  return Array.from(new Set(items.filter((item): item is string => Boolean(item)))).sort();
}

export function getFilterOptionsForScope(scope: SearchScope): Record<string, string[]> {
  const scopeItems = searchItems.filter((item) => item.scope === scope);

  if (scope === "people") {
    return {
      field: cleanStrings(scopeItems.map((i) => i.field)),
      availability: cleanStrings(scopeItems.map((i) => i.availability)),
      location: cleanStrings(scopeItems.map((i) => i.location)),
      profileType: cleanStrings(scopeItems.map((i) => i.profileType)),
      skill: cleanStrings(scopeItems.flatMap((i) => i.skills ?? [])),
      experience: cleanStrings(scopeItems.map((i) => i.experienceLevel)),
      ownership: ["all", "internal", "external"],
    };
  }

  if (scope === "projects") {
    return {
      field: cleanStrings(scopeItems.map((i) => i.field)),
      readiness: cleanStrings(scopeItems.map((i) => i.readiness)),
      location: cleanStrings(scopeItems.map((i) => i.location)),
      technology: cleanStrings(scopeItems.flatMap((i) => i.technologies ?? [])),
      lifecycle: cleanStrings(scopeItems.map((i) => i.status)),
      need: cleanStrings(scopeItems.flatMap((i) => i.collaborationNeeds ?? [])),
      workMode: cleanStrings(scopeItems.map((i) => i.workMode)),
      ownership: ["all", "internal", "external"],
    };
  }

  if (scope === "organizations") {
    return {
      field: cleanStrings(scopeItems.map((i) => i.field)),
      location: cleanStrings(scopeItems.map((i) => i.location)),
      organizationType: cleanStrings(scopeItems.map((i) => i.organizationType)),
      size: cleanStrings(scopeItems.map((i) => i.organizationSize)),
      acceptsCollab: ["Ya", "Tidak"],
      ownership: ["all", "internal", "external"],
    };
  }

  if (scope === "opportunities") {
    return {
      field: cleanStrings(scopeItems.map((i) => i.field)),
      location: cleanStrings(scopeItems.map((i) => i.location)),
      status: cleanStrings(scopeItems.map((i) => i.status)),
      opportunityType: cleanStrings(scopeItems.map((i) => i.opportunityType)),
      requiredSkill: cleanStrings(scopeItems.flatMap((i) => i.requiredSkills ?? [])),
      workMode: cleanStrings(scopeItems.map((i) => i.workMode)),
      deadlineRange: ["7_DAYS", "30_DAYS", "OVER_30_DAYS"],
      ownership: ["all", "internal", "external"],
    };
  }

  return {};
}

export const publicSlugs = {
  projects: ["aqua-loop", "industrial-motor-monitoring", "smart-cooling", "confidential-water-system"],
  profiles: ["maya-pradipta", "nadia-putri", "arya-santoso"],
  organizations: ["nexa-research-lab", "nusantara-labs", "arunika-innovation-hub"],
  opportunities: ["urban-heat-mapping", "embedded-engineer-pilot", "railway-sensor-collaboration"],
} as const;

export * as subscriptionFixtures from "./subscription-fixtures";
