import { PrototypeEntry } from "@/components/prototype/prototype-entry";

const prototypeRoutes = [
  "explore",
  "design-system",
  "search",
  "projects/aqua-loop",
  "projects/industrial-motor-monitoring",
  "projects/smart-cooling",
  "projects/confidential-water-system",
  "projects/cooling-preview",
  "projects/aqua-loop/manage",
  "projects/aqua-loop/contributions",
  "projects/aqua-loop/evidence",
  "projects/aqua-loop/evidence/restricted",
  "projects/aqua-loop/readiness",
  "matches/personal",
  "matches/guest",
  "organization/nusantara",
  "profiles/maya",
  "profiles/maya-pradipta",
  "profiles/nadia-putri",
  "profiles/arya-santoso",
  "organizations/nexa-research-lab",
  "organizations/nusantara-labs",
  "organizations/arunika-innovation-hub",
  "pricing",
  "register",
  "verify-email",
  "onboarding/goals",
  "onboarding/project-source",
  "onboarding/ai-review",
  "onboarding/first-value",
  "home",
  "me",
  "my-projects",
  "discovery",
  "matches/aqua-maya",
  "saved",
  "collaboration",
  "collaboration/new",
  "notifications",
  "settings/privacy",
  "subscription",
  "org/nusantara",
  "org/nusantara/profile",
  "org/nusantara/projects",
  "org/nusantara/search",
  "org/nusantara/shortlist",
  "org/nusantara/pipeline",
  "org/nusantara/members",
  "org/nexa-research-lab",
  "org/nexa-research-lab/projects",
  "organization/nexa-research-lab",
  "organization/nexa-research-lab/profile",
  "organization/nexa-research-lab/projects",
  "organization/nexa-research-lab/search",
  "organization/nexa-research-lab/shortlists",
  "organization/nexa-research-lab/pipeline",
  "organization/nexa-research-lab/members",
  "organization/nexa-research-lab/billing",
  "plans/organization",
  "prototype-map",
  "opportunities/urban-heat",
  "opportunities/urban-heat-mapping",
  "opportunities/embedded-engineer-pilot",
  "opportunities/railway-sensor-collaboration",
  "ai",
  "ai/collaboration-matching",
  "ai/innovation-profile",
  "ai/innovation-workspace",
  "ai/research-gap",
  "ai/novelty-checker",
  "ai/industry-matching",
  "ai/funding-recommendation",
  "ai/commercialization",
];

export function generateStaticParams() {
  return prototypeRoutes.map((route) => ({ path: route.split("/") }));
}

export const dynamicParams = false;

export default function PrototypeCatchAllPage() {
  return <PrototypeEntry />;
}
